version: "2.5"
services:
  ml:
    container_name: ml
    build: ./deploy/ml
    volumes:
      - ./deploy/ml:/app
    ports:
      - 8888:8888
    command: bash -c "uvicorn app:app --host 0.0.0.0 --port 8888 --reload"
    stdin_open: true
    tty: true


  snoc-app:
    container_name: snoc-app
    build: ./deploy/snoc-app
    volumes:
      - ./deploy/snoc-app:/app
    ports:
      - "3000:3000"
    command: bash -c "npm install --legacy-peer-deps && npm start"
    stdin_open: true
    tty: true
    privileged: true
    depends_on:
      - ml


  # Docker Compose file for the stack

  # Build with:
  # docker-compose build

  # Run with:
  # docker-compose up -d